name: Lint
on: workflow_call
jobs:
  build_and_cache:
    name: 'Build and cache'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['16']
      fail-fast: false
    env:
      NODE_ENV: ${{ secrets.NODE_ENV }}
      APP_NAME: ${{ secrets.APP_NAME }}
      PORT: ${{ secrets.PORT }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: npm
      - run: npm ci
      - run: npm run lint
