name: Lint, Build, Test, and Generate Coverage Reports
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  lint:
    uses: codemastermick/github-actions-playground/.github/workflows/lint.yml@main
  build:
    uses: codemastermick/github-actions-playground/.github/workflows/build.yml@main
    needs: lint
    secrets:
      NODE_ENV: ${{ secrets.NODE_ENV }}
      APP_NAME: ${{ secrets.APP_NAME }}
      PORT: ${{ secrets.PORT }}
  test:
    uses: codemastermick/github-actions-playground/.github/workflows/testing.yml@main
    needs: build
    secrets:
      NODE_ENV: ${{ secrets.NODE_ENV }}
      APP_NAME: ${{ secrets.APP_NAME }}
      PORT: ${{ secrets.PORT }}
