name: Test with Coverage
on: workflow_call
jobs:
  test_and_generate_coverage:
    name: 'Test and generate coverage reports'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
      fail-fast: false
    env:
      NODE_ENV: ${{ secrets.NODE_ENV }}
      APP_NAME: ${{ secrets.APP_NAME }}
      PORT: ${{ secrets.PORT }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: npm
      - run: npm ci
      - run: npm run test:coverage
