name: Test with Coverage
on: 
  workflow_call:
    secrets:
      NODE_ENV:
        required: true
      APP_NAME:
        required: true
      PORT:
        required: true
env:
  NODE_ENV: ${{secrets.NODE_ENV}}
  APP_NAME: ${{secrets.APP_NAME}}
  PORT: ${{secrets.PORT}}
jobs:
  test_and_generate_coverage:
    name: 'Test and generate coverage reports'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: npm
      - run: npm ci
      - run: npm run test:coverage
